title: Stackbit Fresh Theme
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: David Berlin
    tagline: My very short bio for the me.
    profile_img: >-
      https://res.cloudinary.com/practicaldev/image/fetch/s--Jlmg62wk--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/125431/a9942bf6-160c-4730-a470-1d2089331e2a.jpg
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: '&copy; All rights reserved.'
    links:
      - text: Made with Stackbit
        url: 'https://www.stackbit.com'
        new_window: true
disableKinds:
  - RSS
